from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import typer
from pydantic import ValidationError

from app.alerts.generator import build_alert_record, load_score_json, save_alert_json
from app.classification.keyword_matcher import (
    classify_documents,
    load_raw_documents,
    save_classified_documents_jsonl,
)
from app.ingestion.failures import (
    ingestion_error_payload,
    load_source_health,
    summarize_source_health_payload,
    update_source_health,
)
from app.ingestion.rss_base import EmptyFeedError, IngestionError, fetch_rss_documents, save_documents_jsonl
from app.live_acceptance import evaluate_live_acceptance, load_live_verification_payload
from app.live_verification import run_live_verification
from app.live_review import build_and_write_live_review_pack
from app.live_history import build_live_history
from app.models import Source, config_summary, format_validation_error, load_configs
from app.runs.snapshots import list_run_snapshots, write_run_snapshot
from app.scoring.baselines import (
    add_baseline_observation,
    baseline_show_payload,
    compare_score_to_baseline,
)
from app.scoring.convergence import (
    load_classified_documents,
    parse_window_days,
    save_score_json,
    score_documents,
)
from app.status import build_scenario_status

# Generated by tools/split_cli_commands.py.
# ruff: noqa: F401

router = typer.Typer(add_completion=False, help="Document classification commands.")

@router.command("classify")
def classify(
    scenario: str = typer.Option(..., "--scenario", help="Scenario ID to classify against."),
    config_dir: Path = typer.Option(
        Path("config"),
        "--config-dir",
        help="Directory containing scenarios.yaml and sources.yaml.",
    ),
    raw_dir: Path = typer.Option(
        Path("data/raw"),
        "--raw-dir",
        help="Directory containing raw JSONL records from ingestion.",
    ),
    processed_dir: Path = typer.Option(
        Path("data/processed"),
        "--processed-dir",
        help="Directory where classified JSONL records are written.",
    ),
    runs_dir: Path = typer.Option(
        Path("data/runs"),
        "--runs-dir",
        help="Directory where run snapshots are written.",
    ),
) -> None:
    """Classify raw documents against one configured scenario and save processed JSONL."""
    try:
        bundle = load_configs(config_dir)
        scenario_config = bundle.get_scenario(scenario)
    except KeyError as exc:
        typer.secho(str(exc), fg=typer.colors.RED, err=True)
        raise typer.Exit(code=1) from exc
    except ValidationError as exc:
        typer.secho("Config validation failed:", fg=typer.colors.RED, err=True)
        typer.echo(format_validation_error(exc), err=True)
        raise typer.Exit(code=1) from exc
    except Exception as exc:
        typer.secho(f"Config loading failed: {exc}", fg=typer.colors.RED, err=True)
        raise typer.Exit(code=1) from exc

    try:
        documents = load_raw_documents(raw_dir)
        classified = classify_documents(documents, scenario_config)
        output_path = save_classified_documents_jsonl(
            classified,
            scenario_id=scenario_config.id,
            processed_dir=processed_dir,
        )
    except Exception as exc:
        write_run_snapshot(
            runs_dir=runs_dir,
            operation="classify",
            subject=scenario,
            status="error",
            parameters={"scenario": scenario},
            inputs={"raw_dir": str(raw_dir)},
            outputs={},
            counts={},
            config_dir=config_dir,
            error={"type": "classification_error", "message": str(exc)},
        )
        typer.secho(f"Classification failed: {exc}", fg=typer.colors.RED, err=True)
        raise typer.Exit(code=1) from exc

    counts = {
        "central": sum(1 for item in classified if item.relevance == "central"),
        "incidental": sum(1 for item in classified if item.relevance == "incidental"),
        "excluded": sum(1 for item in classified if item.relevance == "excluded"),
        "irrelevant": sum(1 for item in classified if item.relevance == "irrelevant"),
    }

    run_path = write_run_snapshot(
        runs_dir=runs_dir,
        operation="classify",
        subject=scenario_config.id,
        status="ok",
        parameters={"scenario": scenario_config.id},
        inputs={"raw_dir": str(raw_dir)},
        outputs={"classified_path": str(output_path)},
        counts={"documents_read": len(documents), "classified": len(classified), **counts},
        config_dir=config_dir,
    )

    payload = {
        "status": "ok",
        "scenario_id": scenario_config.id,
        "documents_read": len(documents),
        "classified": len(classified),
        "output_path": str(output_path),
        "counts": counts,
        "run_snapshot_path": str(run_path),
    }
    typer.echo(json.dumps(payload, indent=2))

