from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import typer
from pydantic import ValidationError

from app.alerts.generator import build_alert_record, load_score_json, save_alert_json
from app.classification.keyword_matcher import (
    classify_documents,
    load_raw_documents,
    save_classified_documents_jsonl,
)
from app.ingestion.failures import (
    ingestion_error_payload,
    load_source_health,
    summarize_source_health_payload,
    update_source_health,
)
from app.ingestion.rss_base import EmptyFeedError, IngestionError, fetch_rss_documents, save_documents_jsonl
from app.live_acceptance import evaluate_live_acceptance, load_live_verification_payload
from app.live_verification import run_live_verification
from app.live_review import build_and_write_live_review_pack
from app.live_history import build_live_history
from app.models import Source, config_summary, format_validation_error, load_configs
from app.runs.snapshots import list_run_snapshots, write_run_snapshot
from app.scoring.baselines import (
    add_baseline_observation,
    baseline_show_payload,
    compare_score_to_baseline,
)
from app.scoring.convergence import (
    load_classified_documents,
    parse_window_days,
    save_score_json,
    score_documents,
)
from app.status import build_scenario_status

# Generated by tools/split_cli_commands.py.
# ruff: noqa: F401

router = typer.Typer(add_completion=False, help="Configuration validation commands.")

@router.command("validate-config")
def validate_config(
    config_dir: Path = typer.Option(
        Path("config"),
        "--config-dir",
        help="Directory containing scenarios.yaml and sources.yaml.",
    )
) -> None:
    """Validate scenario and source configuration files."""
    try:
        bundle = load_configs(config_dir)
    except FileNotFoundError as exc:
        typer.secho(str(exc), fg=typer.colors.RED, err=True)
        raise typer.Exit(code=1) from exc
    except ValidationError as exc:
        typer.secho("Config validation failed:", fg=typer.colors.RED, err=True)
        typer.echo(format_validation_error(exc), err=True)
        raise typer.Exit(code=1) from exc
    except Exception as exc:
        typer.secho(f"Config validation failed: {exc}", fg=typer.colors.RED, err=True)
        raise typer.Exit(code=1) from exc

    typer.echo(json.dumps({"status": "ok", **config_summary(bundle)}, indent=2))

