from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import typer
from pydantic import ValidationError

from app.alerts.generator import build_alert_record, load_score_json, save_alert_json
from app.classification.keyword_matcher import (
    classify_documents,
    load_raw_documents,
    save_classified_documents_jsonl,
)
from app.ingestion.failures import (
    ingestion_error_payload,
    load_source_health,
    summarize_source_health_payload,
    update_source_health,
)
from app.ingestion.rss_base import EmptyFeedError, IngestionError, fetch_rss_documents, save_documents_jsonl
from app.live_acceptance import evaluate_live_acceptance, load_live_verification_payload
from app.live_verification import run_live_verification
from app.live_review import build_and_write_live_review_pack
from app.live_history import build_live_history
from app.models import Source, config_summary, format_validation_error, load_configs
from app.runs.snapshots import list_run_snapshots, write_run_snapshot
from app.scoring.baselines import (
    add_baseline_observation,
    baseline_show_payload,
    compare_score_to_baseline,
)
from app.scoring.convergence import (
    load_classified_documents,
    parse_window_days,
    save_score_json,
    score_documents,
)
from app.status import build_scenario_status

# Generated by tools/split_cli_commands.py.
# ruff: noqa: F401

router = typer.Typer(add_completion=False, help="RSS ingestion commands.")

def _raw_path(raw_dir: Path | str, source_id: str) -> str:
    return str(Path(raw_dir) / f"{source_id}.jsonl")


def _ingest_one_source(
    *,
    source_config: Source,
    limit: int,
    raw_dir: Path,
    runs_dir: Path,
    config_dir: Path,
    replace: bool,
    timeout_seconds: float = 20.0,
) -> dict[str, Any]:
    """Ingest one source and return a structured success or failure payload."""

    parameters = {
        "source": source_config.id,
        "limit": limit,
        "replace": replace,
        "timeout_seconds": timeout_seconds,
    }
    inputs = {"source_url": str(source_config.url)}
    raw_path = _raw_path(raw_dir, source_config.id)

    try:
        documents = fetch_rss_documents(
            source_config,
            limit=limit,
            timeout_seconds=timeout_seconds,
        )
        fetched_entries = int(getattr(documents, "fetched_entries", len(documents)))
        skipped_invalid_entries = int(getattr(documents, "skipped_invalid_entries", 0))
        save_result = save_documents_jsonl(
            documents,
            source_id=source_config.id,
            raw_dir=raw_dir,
            replace=replace,
        )
    except IngestionError as exc:
        error = ingestion_error_payload(source_id=source_config.id, message=str(exc))
        run_path = write_run_snapshot(
            runs_dir=runs_dir,
            operation="ingest",
            subject=source_config.id,
            status="error",
            parameters=parameters,
            inputs=inputs,
            outputs={"raw_path": raw_path},
            counts={
                "fetched": 0,
                "saved": 0,
                "skipped_existing": 0,
            "skipped_invalid_entries": 0,
                "sources_attempted": 1,
                "sources_succeeded": 0,
                "sources_failed": 1,
            },
            config_dir=config_dir,
            error=error,
        )
        update_source_health(
            runs_dir=runs_dir,
            source_id=source_config.id,
            status="error",
            counts={"fetched": 0, "saved": 0, "skipped_existing": 0},
            error=error,
        )
        return {
            "status": "error",
            "operation": "ingest",
            "source_id": source_config.id,
            "source_name": source_config.name,
            "error": error,
            "fetched": 0,
            "saved": 0,
            "skipped_existing": 0,
            "skipped_invalid_entries": 0,
            "raw_path": raw_path,
            "empty_feed": isinstance(exc, EmptyFeedError),
            "run_snapshot_path": str(run_path),
        }
    except Exception as exc:
        error = ingestion_error_payload(
            source_id=source_config.id,
            error_type="unexpected_ingestion_error",
            message=str(exc),
        )
        run_path = write_run_snapshot(
            runs_dir=runs_dir,
            operation="ingest",
            subject=source_config.id,
            status="error",
            parameters=parameters,
            inputs=inputs,
            outputs={"raw_path": raw_path},
            counts={
                "fetched": 0,
                "saved": 0,
                "skipped_existing": 0,
            "skipped_invalid_entries": 0,
                "sources_attempted": 1,
                "sources_succeeded": 0,
                "sources_failed": 1,
            },
            config_dir=config_dir,
            error=error,
        )
        update_source_health(
            runs_dir=runs_dir,
            source_id=source_config.id,
            status="error",
            counts={"fetched": 0, "saved": 0, "skipped_existing": 0},
            error=error,
        )
        return {
            "status": "error",
            "operation": "ingest",
            "source_id": source_config.id,
            "source_name": source_config.name,
            "error": error,
            "fetched": 0,
            "saved": 0,
            "skipped_existing": 0,
            "skipped_invalid_entries": 0,
            "raw_path": raw_path,
            "run_snapshot_path": str(run_path),
        }

    run_path = write_run_snapshot(
        runs_dir=runs_dir,
        operation="ingest",
        subject=source_config.id,
        status="ok",
        parameters=parameters,
        inputs=inputs,
        outputs={"raw_path": save_result.raw_path},
        counts={
            "fetched": save_result.fetched,
            "saved": save_result.saved,
            "skipped_existing": save_result.skipped_existing,
            "fetched_entries": fetched_entries,
            "skipped_invalid_entries": skipped_invalid_entries,
            "sources_attempted": 1,
            "sources_succeeded": 1,
            "sources_failed": 0,
        },
        config_dir=config_dir,
    )
    update_source_health(
        runs_dir=runs_dir,
        source_id=source_config.id,
        status="ok",
        counts={
            "fetched": save_result.fetched,
            "saved": save_result.saved,
            "skipped_existing": save_result.skipped_existing,
            "fetched_entries": fetched_entries,
            "skipped_invalid_entries": skipped_invalid_entries,
        },
    )

    return {
        "status": "ok",
        "operation": "ingest",
        "source_id": source_config.id,
        "source_name": source_config.name,
        "fetched": save_result.fetched,
        "saved": save_result.saved,
        "skipped_existing": save_result.skipped_existing,
            "fetched_entries": fetched_entries,
            "skipped_invalid_entries": skipped_invalid_entries,
        "raw_path": save_result.raw_path,
        "run_snapshot_path": str(run_path),
    }


@router.command("ingest")
def ingest(
    source: str = typer.Option(..., "--source", help="Source ID to ingest, or 'all'."),
    limit: int = typer.Option(10, "--limit", min=1, help="Maximum records to fetch."),
    timeout_seconds: float = typer.Option(
        20.0,
        "--timeout-seconds",
        min=1.0,
        help="Per-source RSS fetch timeout in seconds.",
    ),
    config_dir: Path = typer.Option(
        Path("config"),
        "--config-dir",
        help="Directory containing scenarios.yaml and sources.yaml.",
    ),
    raw_dir: Path = typer.Option(
        Path("data/raw"),
        "--raw-dir",
        help="Directory where raw JSONL records are written.",
    ),
    runs_dir: Path = typer.Option(
        Path("data/runs"),
        "--runs-dir",
        help="Directory where run snapshots are written.",
    ),
    replace: bool = typer.Option(
        False,
        "--replace",
        help="Replace the source JSONL file instead of append/dedupe writing.",
    ),
) -> None:
    """Fetch RSS items and append/dedupe raw records.

    PR 7 supports one source at a time plus ``--source all`` for degraded
    multi-source runs. Failures are returned as structured JSON and written to
    run snapshots; they do not corrupt existing raw files.
    """

    try:
        bundle = load_configs(config_dir)
    except ValidationError as exc:
        typer.secho("Config validation failed:", fg=typer.colors.RED, err=True)
        typer.echo(format_validation_error(exc), err=True)
        raise typer.Exit(code=1) from exc
    except Exception as exc:
        typer.secho(f"Config loading failed: {exc}", fg=typer.colors.RED, err=True)
        raise typer.Exit(code=1) from exc

    if source == "all":
        results = [
            _ingest_one_source(
                source_config=source_config,
                limit=limit,
                raw_dir=raw_dir,
                runs_dir=runs_dir,
                config_dir=config_dir,
                replace=replace,
                timeout_seconds=timeout_seconds,
            )
            for source_config in bundle.enabled_sources
        ]
        failures = [result for result in results if result["status"] == "error"]
        successes = [result for result in results if result["status"] == "ok"]

        if not failures:
            status = "ok"
        elif successes:
            status = "degraded"
        else:
            status = "error"

        global_run_path = write_run_snapshot(
            runs_dir=runs_dir,
            operation="ingest",
            subject="all",
            status=status,
            parameters={
            "source": "all",
            "limit": limit,
            "replace": replace,
            "timeout_seconds": timeout_seconds,
        },
            inputs={"source_ids": [item.id for item in bundle.enabled_sources]},
            outputs={
                "raw_paths": [
                    result["raw_path"] for result in results if result.get("raw_path")
                ]
            },
            counts={
                "sources_attempted": len(results),
                "sources_succeeded": len(successes),
                "sources_failed": len(failures),
                "fetched": sum(int(result.get("fetched", 0)) for result in results),
                "saved": sum(int(result.get("saved", 0)) for result in results),
                "skipped_existing": sum(
                    int(result.get("skipped_existing", 0)) for result in results
                ),
                "skipped_invalid_entries": sum(
                    int(result.get("skipped_invalid_entries", 0)) for result in results
                ),
            },
            config_dir=config_dir,
            error={
                "type": "degraded_ingestion",
                "message": "One or more sources failed during ingestion.",
                "failed_sources": [failure["source_id"] for failure in failures],
            }
            if failures
            else None,
        )

        payload = {
            "status": status,
            "operation": "ingest",
            "sources_attempted": len(results),
            "sources_succeeded": len(successes),
            "sources_failed": len(failures),
            "fetched": sum(int(result.get("fetched", 0)) for result in results),
            "saved": sum(int(result.get("saved", 0)) for result in results),
            "skipped_existing": sum(
                int(result.get("skipped_existing", 0)) for result in results
            ),
            "skipped_invalid_entries": sum(
                int(result.get("skipped_invalid_entries", 0)) for result in results
            ),
            "results": results,
            "failures": failures,
            "run_snapshot_path": str(global_run_path),
        }
        typer.echo(json.dumps(payload, indent=2))
        if status == "error":
            raise typer.Exit(code=1)
        return

    try:
        source_config = bundle.get_source(source)
    except KeyError as exc:
        error = ingestion_error_payload(
            source_id=source,
            error_type="unknown_source",
            message=str(exc),
        )
        run_path = write_run_snapshot(
            runs_dir=runs_dir,
            operation="ingest",
            subject=source,
            status="error",
            parameters={
            "source": source,
            "limit": limit,
            "replace": replace,
            "timeout_seconds": timeout_seconds,
        },
            inputs={},
            outputs={"raw_path": _raw_path(raw_dir, source)},
            counts={
                "fetched": 0,
                "saved": 0,
                "skipped_existing": 0,
            "skipped_invalid_entries": 0,
                "sources_attempted": 1,
                "sources_succeeded": 0,
                "sources_failed": 1,
            },
            config_dir=config_dir,
            error=error,
        )
        update_source_health(
            runs_dir=runs_dir,
            source_id=source,
            status="error",
            counts={"fetched": 0, "saved": 0, "skipped_existing": 0},
            error=error,
        )
        payload = {
            "status": "error",
            "operation": "ingest",
            "source_id": source,
            "error": error,
            "fetched": 0,
            "saved": 0,
            "skipped_existing": 0,
            "skipped_invalid_entries": 0,
            "raw_path": _raw_path(raw_dir, source),
            "run_snapshot_path": str(run_path),
        }
        typer.echo(json.dumps(payload, indent=2))
        raise typer.Exit(code=1) from exc

    if not source_config.enabled:
        error = ingestion_error_payload(
            source_id=source,
            error_type="source_disabled",
            message=f"Source is disabled: {source}",
        )
        raw_path = _raw_path(raw_dir, source)
        run_path = write_run_snapshot(
            runs_dir=runs_dir,
            operation="ingest",
            subject=source,
            status="error",
            parameters={
            "source": source,
            "limit": limit,
            "replace": replace,
            "timeout_seconds": timeout_seconds,
        },
            inputs={"source_url": str(source_config.url)},
            outputs={"raw_path": raw_path},
            counts={
                "fetched": 0,
                "saved": 0,
                "skipped_existing": 0,
            "skipped_invalid_entries": 0,
                "sources_attempted": 1,
                "sources_succeeded": 0,
                "sources_failed": 1,
            },
            config_dir=config_dir,
            error=error,
        )
        update_source_health(
            runs_dir=runs_dir,
            source_id=source,
            status="error",
            counts={"fetched": 0, "saved": 0, "skipped_existing": 0},
            error=error,
        )
        payload = {
            "status": "error",
            "operation": "ingest",
            "source_id": source,
            "error": error,
            "fetched": 0,
            "saved": 0,
            "skipped_existing": 0,
            "skipped_invalid_entries": 0,
            "raw_path": raw_path,
            "run_snapshot_path": str(run_path),
        }
        typer.echo(json.dumps(payload, indent=2))
        raise typer.Exit(code=1)

    payload = _ingest_one_source(
        source_config=source_config,
        limit=limit,
        raw_dir=raw_dir,
        runs_dir=runs_dir,
        config_dir=config_dir,
        replace=replace,
        timeout_seconds=timeout_seconds,
    )
    typer.echo(json.dumps(payload, indent=2))
    if payload["status"] == "error":
        raise typer.Exit(code=1)

