from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import typer
from pydantic import ValidationError

from app.alerts.generator import build_alert_record, load_score_json, save_alert_json
from app.classification.keyword_matcher import (
    classify_documents,
    load_raw_documents,
    save_classified_documents_jsonl,
)
from app.ingestion.failures import (
    ingestion_error_payload,
    load_source_health,
    summarize_source_health_payload,
    update_source_health,
)
from app.ingestion.rss_base import EmptyFeedError, IngestionError, fetch_rss_documents, save_documents_jsonl
from app.live_acceptance import evaluate_live_acceptance, load_live_verification_payload
from app.live_verification import run_live_verification
from app.live_review import build_and_write_live_review_pack
from app.live_history import build_live_history
from app.models import Source, config_summary, format_validation_error, load_configs
from app.runs.snapshots import list_run_snapshots, write_run_snapshot
from app.scoring.baselines import (
    add_baseline_observation,
    baseline_show_payload,
    compare_score_to_baseline,
)
from app.scoring.convergence import (
    load_classified_documents,
    parse_window_days,
    save_score_json,
    score_documents,
)
from app.status import build_scenario_status

# Generated by tools/split_cli_commands.py.
# ruff: noqa: F401

router = typer.Typer(add_completion=False, help="Run snapshot inspection commands.")

@router.command("list")
def list_runs(
    runs_dir: Path = typer.Option(
        Path("data/runs"),
        "--runs-dir",
        help="Directory containing run snapshots.",
    )
) -> None:
    """List run snapshots as stable JSON."""
    snapshots = list_run_snapshots(runs_dir)
    payload = {
        "status": "ok",
        "run_count": len(snapshots),
        "runs": snapshots,
    }
    typer.echo(json.dumps(payload, indent=2))


@router.command("health")
def source_health(
    runs_dir: Path = typer.Option(
        Path("data/runs"),
        "--runs-dir",
        help="Directory containing source health records.",
    )
) -> None:
    """Return latest source-health status as stable JSON."""
    payload = load_source_health(runs_dir)
    summary = summarize_source_health_payload(payload)
    typer.echo(json.dumps({"status": "ok", **payload, "summary": summary}, indent=2))

